<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class CurrencyTableSeeder extends Seeder 
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $currencies = [
            [ 'id' => 1, 'country' => 'US Dollar', 'currency_code' => 'USD', 'currency_symbol' => '$', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 2, 'country' => 'Canadian Dollar', 'currency_code' => 'CAD', 'currency_symbol' => 'CA$', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 3, 'country' => 'Euro', 'currency_code' => 'EUR', 'currency_symbol' => '€', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 4, 'country' => 'United Arab Emirates Dirham', 'currency_code' => 'AED', 'currency_symbol' => 'د.إ.‏', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 5, 'country' => 'Afghan Afghani', 'currency_code' => 'AFN', 'currency_symbol' => '؋', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 6, 'country' => 'Albanian Lek', 'currency_code' => 'ALL', 'currency_symbol' => 'L', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 7, 'country' => 'Armenian Dram', 'currency_code' => 'AMD', 'currency_symbol' => '֏', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 8, 'country' => 'Argentine Peso', 'currency_code' => 'ARS', 'currency_symbol' => '$', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 9, 'country' => 'Australian Dollar', 'currency_code' => 'AUD', 'currency_symbol' => '$', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 10, 'country' => 'Azerbaijani Manat', 'currency_code' => 'AZN', 'currency_symbol' => '₼', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 11, 'country' => 'Bosnia-Herzegovina Convertible Mark', 'currency_code' => 'BAM', 'currency_symbol' => 'KM', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 12, 'country' => 'Bangladeshi Taka', 'currency_code' => 'BDT', 'currency_symbol' => '৳', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 13, 'country' => 'Bulgarian Lev', 'currency_code' => 'BGN', 'currency_symbol' => 'лв.', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 14, 'country' => 'Bahraini Dinar', 'currency_code' => 'BHD', 'currency_symbol' => 'د.ب.‏', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 15, 'country' => 'Burundian Franc', 'currency_code' => 'BIF', 'currency_symbol' => 'FBu', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 16, 'country' => 'Brunei Dollar', 'currency_code' => 'BND', 'currency_symbol' => 'B$', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 17, 'country' => 'Bolivian Boliviano', 'currency_code' => 'BOB', 'currency_symbol' => 'Bs', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 18, 'country' => 'Brazilian Real', 'currency_code' => 'BRL', 'currency_symbol' => 'R$', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 19, 'country' => 'Botswanan Pula', 'currency_code' => 'BWP', 'currency_symbol' => 'P', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 20, 'country' => 'Belarusian Ruble', 'currency_code' => 'BYN', 'currency_symbol' => 'Br', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 21, 'country' => 'Belize Dollar', 'currency_code' => 'BZD', 'currency_symbol' => '$', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 22, 'country' => 'Congolese Franc', 'currency_code' => 'CDF', 'currency_symbol' => 'FC', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 23, 'country' => 'Swiss Franc', 'currency_code' => 'CHF', 'currency_symbol' => 'CHf', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 24, 'country' => 'Chilean Peso', 'currency_code' => 'CLP', 'currency_symbol' => '$', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 25, 'country' => 'Chinese Yuan', 'currency_code' => 'CNY', 'currency_symbol' => '¥', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 26, 'country' => 'Colombian Peso', 'currency_code' => 'COP', 'currency_symbol' => '$', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 27, 'country' => 'Costa Rican Colón', 'currency_code' => 'CRC', 'currency_symbol' => '₡', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 28, 'country' => 'Cape Verdean Escudo', 'currency_code' => 'CVE', 'currency_symbol' => '$', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 29, 'country' => 'Czech Republic Koruna', 'currency_code' => 'CZK', 'currency_symbol' => 'Kč', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 30, 'country' => 'Djiboutian Franc', 'currency_code' => 'DJF', 'currency_symbol' => 'Fdj', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 31, 'country' => 'Danish Krone', 'currency_code' => 'DKK', 'currency_symbol' => 'Kr.', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 32, 'country' => 'Dominican Peso', 'currency_code' => 'DOP', 'currency_symbol' => 'RD$', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 33, 'country' => 'Algerian Dinar', 'currency_code' => 'DZD', 'currency_symbol' => 'د.ج.‏', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 34, 'country' => 'Estonian Kroon', 'currency_code' => 'EEK', 'currency_symbol' => 'kr', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 35, 'country' => 'Egyptian Pound', 'currency_code' => 'EGP', 'currency_symbol' => 'E£‏', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 36, 'country' => 'Eritrean Nakfa', 'currency_code' => 'ERN', 'currency_symbol' => 'Nfk', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 37, 'country' => 'Ethiopian Birr', 'currency_code' => 'ETB', 'currency_symbol' => 'Br', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 38, 'country' => 'British Pound Sterling', 'currency_code' => 'GBP', 'currency_symbol' => '£', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 39, 'country' => 'Georgian Lari', 'currency_code' => 'GEL', 'currency_symbol' => 'GEL', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 40, 'country' => 'Ghanaian Cedi', 'currency_code' => 'GHS', 'currency_symbol' => 'GH¢', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 41, 'country' => 'Guinean Franc', 'currency_code' => 'GNF', 'currency_symbol' => 'FG', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 42, 'country' => 'Guatemalan Quetzal', 'currency_code' => 'GTQ', 'currency_symbol' => 'Q', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 43, 'country' => 'Hong Kong Dollar', 'currency_code' => 'HKD', 'currency_symbol' => 'HK$', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 44, 'country' => 'Honduran Lempira', 'currency_code' => 'HNL', 'currency_symbol' => 'L', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 45, 'country' => 'Croatian Kuna', 'currency_code' => 'HRK', 'currency_symbol' => 'kn', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 46, 'country' => 'Hungarian Forint', 'currency_code' => 'HUF', 'currency_symbol' => 'Ft', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 47, 'country' => 'Indonesian Rupiah', 'currency_code' => 'IDR', 'currency_symbol' => 'Rp', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 48, 'country' => 'Israeli New Sheqel', 'currency_code' => 'ILS', 'currency_symbol' => '₪', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 49, 'country' => 'Indian Rupee', 'currency_code' => 'INR', 'currency_symbol' => '₹', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 50, 'country' => 'Iraqi Dinar', 'currency_code' => 'IQD', 'currency_symbol' => 'ع.د', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 51, 'country' => 'Iranian Rial', 'currency_code' => 'IRR', 'currency_symbol' => '﷼', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 52, 'country' => 'Icelandic Króna', 'currency_code' => 'ISK', 'currency_symbol' => 'kr', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 53, 'country' => 'Jamaican Dollar', 'currency_code' => 'JMD', 'currency_symbol' => '$', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 54, 'country' => 'Jordanian Dinar', 'currency_code' => 'JOD', 'currency_symbol' => 'د.ا‏', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 55, 'country' => 'Japanese Yen', 'currency_code' => 'JPY', 'currency_symbol' => '¥', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 56, 'country' => 'Kenyan Shilling', 'currency_code' => 'KES', 'currency_symbol' => 'Ksh', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 57, 'country' => 'Cambodian Riel', 'currency_code' => 'KHR', 'currency_symbol' => '៛', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 58, 'country' => 'Comorian Franc', 'currency_code' => 'KMF', 'currency_symbol' => 'FC', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 59, 'country' => 'South Korean Won', 'currency_code' => 'KRW', 'currency_symbol' => 'CF', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 60, 'country' => 'Kuwaiti Dinar', 'currency_code' => 'KWD', 'currency_symbol' => 'د.ك.‏', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 61, 'country' => 'Kazakhstani Tenge', 'currency_code' => 'KZT', 'currency_symbol' => '₸.', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 62, 'country' => 'Lebanese Pound', 'currency_code' => 'LBP', 'currency_symbol' => 'ل.ل.‏', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 63, 'country' => 'Sri Lankan Rupee', 'currency_code' => 'LKR', 'currency_symbol' => 'Rs', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 64, 'country' => 'Lithuanian Litas', 'currency_code' => 'LTL', 'currency_symbol' => 'Lt', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 65, 'country' => 'Latvian Lats', 'currency_code' => 'LVL', 'currency_symbol' => 'Ls', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 66, 'country' => 'Libyan Dinar', 'currency_code' => 'LYD', 'currency_symbol' => 'د.ل.‏', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 67, 'country' => 'Moroccan Dirham', 'currency_code' => 'MAD', 'currency_symbol' => 'د.م.‏', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 68, 'country' => 'Moldovan Leu', 'currency_code' => 'MDL', 'currency_symbol' => 'L', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 69, 'country' => 'Malagasy Ariary', 'currency_code' => 'MGA', 'currency_symbol' => 'Ar', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 70, 'country' => 'Macedonian Denar', 'currency_code' => 'MKD', 'currency_symbol' => 'Ден', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 71, 'country' => 'Myanma Kyat', 'currency_code' => 'MMK', 'currency_symbol' => 'K', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 72, 'country' => 'Macanese Pataca', 'currency_code' => 'MOP', 'currency_symbol' => 'MOP$', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 73, 'country' => 'Mauritian Rupee', 'currency_code' => 'MUR', 'currency_symbol' => 'Rs', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 74, 'country' => 'Mexican Peso', 'currency_code' => 'MXN', 'currency_symbol' => '$', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 75, 'country' => 'Malaysian Ringgit', 'currency_code' => 'MYR', 'currency_symbol' => 'RM', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 76, 'country' => 'Mozambican Metical', 'currency_code' => 'MZN', 'currency_symbol' => 'MT', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 77, 'country' => 'Namibian Dollar', 'currency_code' => 'NAD', 'currency_symbol' => 'N$', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 78, 'country' => 'Nigerian Naira', 'currency_code' => 'NGN', 'currency_symbol' => '₦', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 79, 'country' => 'Nicaraguan Córdoba', 'currency_code' => 'NIO', 'currency_symbol' => 'C$', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 80, 'country' => 'Norwegian Krone', 'currency_code' => 'NOK', 'currency_symbol' => 'kr', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 81, 'country' => 'Nepalese Rupee', 'currency_code' => 'NPR', 'currency_symbol' => 'Re.', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 82, 'country' => 'New Zealand Dollar', 'currency_code' => 'NZD', 'currency_symbol' => '$', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 83, 'country' => 'Omani Rial', 'currency_code' => 'OMR', 'currency_symbol' => 'ر.ع.‏', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 84, 'country' => 'Panamanian Balboa', 'currency_code' => 'PAB', 'currency_symbol' => 'B/.', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 85, 'country' => 'Peruvian Nuevo Sol', 'currency_code' => 'PEN', 'currency_symbol' => 'S/', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 86, 'country' => 'Philippine Peso', 'currency_code' => 'PHP', 'currency_symbol' => '₱', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 87, 'country' => 'Pakistani Rupee', 'currency_code' => 'PKR', 'currency_symbol' => 'Rs', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 88, 'country' => 'Polish Zloty', 'currency_code' => 'PLN', 'currency_symbol' => 'zł', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 89, 'country' => 'Paraguayan Guarani', 'currency_code' => 'PYG', 'currency_symbol' => '₲', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 90, 'country' => 'Qatari Rial', 'currency_code' => 'QAR', 'currency_symbol' => 'ر.ق.‏', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 91, 'country' => 'Romanian Leu', 'currency_code' => 'RON', 'currency_symbol' => 'lei', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 92, 'country' => 'Serbian Dinar', 'currency_code' => 'RSD', 'currency_symbol' => 'din.', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 93, 'country' => 'Russian Ruble', 'currency_code' => 'RUB', 'currency_symbol' => '₽.', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 94, 'country' => 'Rwandan Franc', 'currency_code' => 'RWF', 'currency_symbol' => 'FRw', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 95, 'country' => 'Saudi Riyal', 'currency_code' => 'SAR', 'currency_symbol' => 'ر.س.‏', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 96, 'country' => 'Sudanese Pound', 'currency_code' => 'SDG', 'currency_symbol' => 'ج.س.', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 97, 'country' => 'Swedish Krona', 'currency_code' => 'SEK', 'currency_symbol' => 'kr', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 98, 'country' => 'Singapore Dollar', 'currency_code' => 'SGD', 'currency_symbol' => '$', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 99, 'country' => 'Somali Shilling', 'currency_code' => 'SOS', 'currency_symbol' => 'Sh.so.', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 100, 'country' => 'Syrian Pound', 'currency_code' => 'SYP', 'currency_symbol' => 'LS‏', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 101, 'country' => 'Thai Baht', 'currency_code' => 'THB', 'currency_symbol' => '฿', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 102, 'country' => 'Tunisian Dinar', 'currency_code' => 'TND', 'currency_symbol' => 'د.ت‏', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 103, 'country' => 'Tongan Paʻanga', 'currency_code' => 'TOP', 'currency_symbol' => 'T$', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 104, 'country' => 'Turkish Lira', 'currency_code' => 'TRY', 'currency_symbol' => '₺', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 105, 'country' => 'Trinidad and Tobago Dollar', 'currency_code' => 'TTD', 'currency_symbol' => '$', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 106, 'country' => 'New Taiwan Dollar', 'currency_code' => 'TWD', 'currency_symbol' => 'NT$', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 107, 'country' => 'Tanzanian Shilling', 'currency_code' => 'TZS', 'currency_symbol' => 'TSh', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 108, 'country' => 'Ukrainian Hryvnia', 'currency_code' => 'UAH', 'currency_symbol' => '₴', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 109, 'country' => 'Ugandan Shilling', 'currency_code' => 'UGX', 'currency_symbol' => 'USh', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 110, 'country' => 'Uruguayan Peso', 'currency_code' => 'UYU', 'currency_symbol' => '$', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 111, 'country' => 'Uzbekistan Som', 'currency_code' => 'UZS', 'currency_symbol' => 'so\'m', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 112, 'country' => 'Venezuelan Bolívar', 'currency_code' => 'VEF', 'currency_symbol' => 'Bs.F.', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 113, 'country' => 'Vietnamese Dong', 'currency_code' => 'VND', 'currency_symbol' => '₫', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 114, 'country' => 'CFA Franc BEAC', 'currency_code' => 'XAF', 'currency_symbol' => 'FCFA', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 115, 'country' => 'CFA Franc BCEAO', 'currency_code' => 'XOF', 'currency_symbol' => 'CFA', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 116, 'country' => 'Yemeni Rial', 'currency_code' => 'YER', 'currency_symbol' => '﷼‏', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 117, 'country' => 'South African Rand', 'currency_code' => 'ZAR', 'currency_symbol' => 'R', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 118, 'country' => 'Zambian Kwacha', 'currency_code' => 'ZMK', 'currency_symbol' => 'ZK', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()],
            [ 'id' => 119, 'country' => 'Zimbabwean Dollar', 'currency_code' => 'ZWL', 'currency_symbol' => 'Z$', 'exchange_rate' => '1.00', 'created_at' => now(), 'updated_at' => now()]
        ];

        DB::table('currencies')->insert($currencies);
    }
}